name: Build and upload image

on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string

      imageTag:
        required: true
        type: string

      dockerfile:
        required: true
        type: string

    secrets:
      ghToken:
        required: true

env:
  REGISTRY: ghcr.io/ateleris/vllm

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ inputs.actor }}
          password: ${{ secrets.ghToken }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.REGISTRY }}:${{ inputs.imageTag }}